version: 0.2

phases:
  build:
    commands:
      - echo Building...
  post_build:
    commands:
      - echo Build completed
artifacts:
  files:
    - index.html
    - appspec.yml     
  discard-paths: yes
  
 